### ISSUE TITLE
How to update CSS?

### ISSUE THREAD

**Issue by ggeisler** [matthewelsom/LivingStyleGuide#1]
Thanks for sharing this project. I have similar goals for a style guide and this looks like your work could be a great headstart for my project. I have it cloned locally and have no trouble updating content, but I can't seem to figure out how to update the styles. For example, I've updated the `$base-font-family` and `$base-font-color` variables in `styleguide/_scss/abstracts/_variables.scss` but see no difference from the default styling when I refresh the site. I've enabled the sass configuration lines 37-39 in `config.yml` (and restarted the server) but that doesn't seem to make a difference

It looks like you're still working on the "Editing the Styleguide" part of the documentation but I'm hoping in the meantime you could explain the steps necessary to update the styleguide styling, such as the default font and, say, the sidebar background color as examples?

It's possible I just don't understand the site structure properly (e.g. what's the relationship between the `src` and `styleguide` directories?) but nothing I try is producing style updates. Thanks.

**Comment by matthewelsom** [comment]
Hi @ggeisler,  you're right, I haven't got round to completing all of the documentation yet. Apologies for that, but, you are heading in the right direction!

To edit the style guide shell styles you need to:  

1. Build or Serve the tool with `config.yml` lines 37 - 39 disabled and lines 120 - 122 enabled 

```
#sass: 
#  sass_dir: styleguide/_scss
#  style: :compressed

sass:
  sass_dir: src/assets/_scss 
  style: :compressed      
```

2. Copy the following **generated** css file: `/_site/src/assets/css/styles.css`.
3. Paste that css file to the following location: `/src/assets/css/`. This will preserve the pattern styles you have already created.
4. If you are using `jekyll serve` - stop it.
5. Open the pattern styles scss file `/src/assets/css/styles.scss`, comment out the front matter on line 1-2 like this:

```
//---
//# Enable this frontmatter to output styles.css
//---
//Vendor
@import "vendor/__vendor-dir";
...
```
6. Open the style guide styles scss file `/styleguide/css/styleguide.scss`, uncomment out the front matter on line 1-2 like this:
```
---
# Enable this frontmatter to output styleguide.css 
---
//Vendor
@import "vendor/__vendor-dir";
...
```
7. Delete the following file: `/styleguide/css/styleguide.css`
8. Update the `_config.yml` file, reversing the disabled/enabled stylesheet references: 
```
sass: 
  sass_dir: styleguide/_scss
  style: :compressed

#sass:
#  sass_dir: src/assets/_scss 
#  style: :compressed      
```
9. Run `jekyll b` or `jekyll s` - `styles.scss` will not generate, `styleguide.scss` will generate.

This process essentially tells Jekyll to only generate the style guide shell related styles, not the pattern styles. You can now change **any** of the `.scss` files inside the `/styleguide/_scss/` folder, and see the changes to the style guide shell. E.g. 

`/styleguide/_scss/components/_sidebar.scss`
```
.sg_sidebar {
  background: lighten($black, 4%); // Change to whatever sidebar color you want.
}
```

`/styleguide/_scss/abstracts/_variables.scss`
```
// Font Sizing
$base-font-size: 16px; // Change the base font size to whatever you want
```

FYI: Fonts are called here: `/styleguide/_scss/abstracts/_fonts.scss`

#### Important

- When you are done you need to copy the generated shell css file `_site/styleguide/css/styleguide.css` file and paste it here: `/styleguide/css/`
- Then stop `jekyll serve` and undo the steps above to reset the system. 

In writing this, I realise how overly-complicated this may be, and I wonder if there is a better way of doing this... Could you let me know if a) the above makes sense, and, b) you have any thoughts on how this can be done differently/better? 

Any ideas you have would be helpful. Also, please continue to flag any issues you spot or help you need - This will help me to improve my documentation. 

Thanks

**Comment by ggeisler** [comment]
Thanks @matthewelsom for your detailed instructions! I totally get that this is a work in progress and am happy to help as I can with testing and potentially offering documentation suggestions.

Your instructions do help me understand how things work a bit better. But at this point I think I'm still stuck, at step 9. I've tried things twice so hopefully it's not user error on my part. The issue is when I run the server again after doing the first eight steps, the expected `styleguide.css` file doesn't look like it was generated. I get a 404:

> styleguide.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

And in my project I can see that in the `/_site/styleguide/css/` directory there is only `styleguide.scss` and no `styleguide.css`. This is with lines 37 - 39 enabled in `_config.yml` and the frontmatter lines in `/styleguide/css/styleguide.scss` uncommented.

You might have already done this when writing up your instructions, but maybe you could try going through your steps on a fresh clone and see if you end up with the same error as me?

**Comment by matthewelsom** [comment]
Hey @ggeisler - thanks for following those steps! I figured it out...

Firstly, I made an error in step 2, I missed out the `src` directory in the filename, it should say. 

2. Copy the following generated css file: `/_site/src/assets/css/styles.css`.

I took your advice and ran a fresh clone, then followed my instructions. The steps are correct, but there is an issue with the Front Matter in the `styleguide.scss` file (step 6), the comment at the start of the file is preventing it from generating! 🤦

Move the comment in `styleguide.scss`and it will correctly output to `/_site/styleguide/css/styleguide.css` 

```
---
# Enable this frontmatter to output styleguide.css 
---
//Vendor
@import "vendor/__vendor-dir";
...
```

I updated my previous comment to reflect these changes, and I pushed a fix to the repo.

**Comment by ggeisler** [comment]
👍 Your updates solved my problem, @matthewelsom, thanks! I'll work on my customizations over the next week and keep notes to share with you if I have any ideas that might help with documentation, etc. I'll let you decide when to close this issue.
