### ISSUE TITLE
including patterns within other patterns

### ISSUE THREAD

**Issue by bw1984** [matthewelsom/LivingStyleGuide#2]
I have very little experience with jekyll but have just this morning spun up a copy of the styleguide generator to kick the tyres. The first issue I encountered was based on our need to embed patterns within other 'larger' patterns. Since most of our projects follow atomic principles its very necessary for us to be able to maintain styles and markup at an atomic level, knowing that changes will propagate upwards into larger components.

With this in mind i opened up the full-width.html example you have in your repo but see that the `blockquote` markup was hardcoded. 

I have made a quick modification to that file to see if i can import an existing pattern, so i added the following lines to see what would happen;

```
{% assign pattern_url = '/src/patterns/components/blockquote/blockquote.html' %}
{% include pattern_block.html %}
```

this seemed to work as designed but unfortunately the pattern_block.html template contains both the markup itself and also the title, description, code block etc... which was more than i wanted to embed. So what I have done is created a new template within _includes called `pattern_block_raw.html` which looks like this;

```
{% for pattern in site.pages %}
{% if pattern.url contains pattern_url %}

	{{ pattern.content }}

{% endif %}
{% endfor %}
```

I then updated my include call to use `pattern_block_raw.html` instead. This works great, but because I dont necessarily understand the workings of jekyll i just wondered if theres a 'cleaner' way to achieve this?

The main reason I ask is that it currently requires 2 lines for each include, and i imagine there was be a way to do this with a single include call? My larger patterns may begin to get cluttered quickly with 2 calls per include, especially when the second call is always the same.

**Comment by matthewelsom** [comment]
Hi @bw1984 thanks for the feedback and raising the question. 

So, I didn't really design this system to accommodate atomic principles, that is not really a workflow I follow, and includes, inside includes, inside includes, etc. can get quite complex with Jekyll. 

That said, I think the approach you are taking towards making this tool atomic-ready is not a bad one, and I am glad you managed to get something to work to start with. 

You got me thinking about a simpler way to include the pattern - so in the latest release I have removed the need to 'assign' the pattern url. Instead the url is specified using a variable in the `pattern_block.html` to include a pattern you can now do this:

`{% include pattern_block.html url='/src/patterns/components/button/default_button.html' %}`

There is full documentation of this change [here](https://jekyllstyleguide.com/docs/about/01-getting-started.html#adding-documentation).

Using the same principle you could simplify your approach to generate a 'raw' pattern. Consider the following... (note I have not published this code as I am not sure if I want to support it just yet)

Add an if statement in `pattern_block.html` that checks the 'format' variable is equal to 'raw'.

```
{% for pattern in site.pages %}
{% if pattern.url contains include.url %}
{% if include.format == 'raw' %}
{{ pattern.content }}
{% else %}
<section class="sg_pattern" id="{{ pattern.title | slugify }}" >
  <div class="title">
    <a class="permalink" href="{{ pattern.title | slugify | prepend: '#' }}"><i class="icon" data-icon="link"></i></a><div class="header typo_eagle">{{ pattern.title }}</div> 
    {% if pattern.maturity %}<div class="sg_label {{ pattern.maturity }}">{{ pattern.maturity }}</div>{% endif %}
  </div>
  {% if pattern.control != 'exclude' %}<div class="sg_pattern_control" data-styles="{{ pattern.styles }}">
    <a href="javascript:void(0)" title="View Source Code" class="sg_helper_code button"><i class="icon" data-icon="code"></i></a>  
    <a href="javascript:void(0)" title="Open in new window" class="sg_helper_open button" href="{{ site.baseurl }}{{ pattern_url }}" target="_blank"><i class="icon" data-icon="screen_share"></i></a>
  </div>{% endif %}
  <div class="sg_viewport">
    <iframe frameborder="0" scrolling="no" src="{{ site.baseurl }}{{ include.url }}" allowfullscreen></iframe>
  </div>
  <div class="sg_code" data-styles="{{ pattern.styles }}">
<!--  Get all Patterns, find the the Pattern that matches the pattern_url, print the Pattern code -->
{% highlight html %}
{{ pattern.content }}
{% endhighlight %}
  </div>
</section>
{% endif %}
{% endif %}
{% endfor %}
```

Include the pattern and specify the `format='raw'` - this will result in only displaying `{{ pattern.content }} `

`{% include pattern_block.html url='/src/patterns/components/button/default_button.html' format='raw' %}`

That does away the need to create a 'pattern_raw.html' file.

Hope that helps for now!

**Comment by bw1984** [comment]
Amazing! Thats exactly what I was looking for. I'm curious to see what happens when i try to use nested includes in the way you mentioned. I dont necessarily mind the nesting becoming complicated so long as i dont need to update the same pattern in multiple places. Thanks very much 👍

**Comment by matthewelsom** [comment]
Great, glad that helped. I'll close this for now, but, I would be interested to see how your atomic version works out 😎
